import js from "@eslint/js";
import globals from "globals";

export default [
  {
    // dist/ is generated by `npm run build` from src/ and not linted.
    ignores: ["node_modules/", "dist/"],
  },
  js.configs.recommended,
  {
    // The card's source: ES modules that run in the browser, bundled by esbuild.
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: globals.browser,
    },
  },
  {
    // The test suite, the build script and this config run under Node as ES
    // modules.
    files: ["test/**/*.mjs", "scripts/**/*.mjs", "eslint.config.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: globals.node,
    },
  },
];
