// Bundles src/ into the single file Home Assistant loads. The output is kept
// readable on purpose: it is what ends up in a user's browser dev tools.
import { build } from "esbuild";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));

const banner = `/*
 * donetick-chores-card - generated by \`npm run build\` from src/.
 * Do not edit this file: change src/, rebuild, and commit the result.
 */`;

await build({
  absWorkingDir: root,
  entryPoints: ["src/index.js"],
  outfile: "dist/donetick-chores-card.js",
  bundle: true,
  format: "iife",
  target: "es2022",
  minify: false,
  legalComments: "none",
  banner: { js: banner },
  logLevel: "info",
});
